<!DOCTYPE html>
<html>
<head>
    <title>ItsolutionStuff.com</title>
</head>
<body>
    <h1>Kyonority</h1>
    <p>This is an autogenerated receipt.</p>

    <p>You have donated RM{{ $details['price'] }} to {{ $details['receiver'] }} on {{ $details['date'] }}.</p>
   
    <p>Thank you for your contribution!</p>
</body>
</html>